spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  security:
    user:
      name: user
      password: pass123
      
security:
  oauth2:
    client:
      client-id: web
      client-secret: pin
      access-token-validity-seconds: 18000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
third:
  party:
    api:
      service:
        uri: http://google.co.in


